name: controldesellos
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # PDF
  syncfusion_flutter_pdf: ^26.1.35
  syncfusion_flutter_core: ^26.1.35
  shared_preferences: ^2.0.15
  pdfx: ^2.5.0          # <--- AÑADIR ESTA LÍNEA
  image: ^4.0.17        # <--- AÑADIR ESTA LÍNEA

  # Selección de archivos
  file_picker: 

  # Guardar archivos en dispositivo
  path_provider: ^2.0.11

  # Abrir archivos
  open_file: ^3.5.4

  # Arrastrar y soltar
  desktop_drop: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^2.1.1

flutter:
  uses-material-design: true
  
msix_config:
  display_name: ControlDeSellos
  publisher_display_name: fvsoftremsolucion
  identity_name: fvsoftremsolucion.ControlDeSellos
  publisher: "CN=299D70E9-BB6D-4508-AD59-899C22E7C9C9"
  msix_version: 1.0.0.1
  logo_path: windows/runner/resources/app_icon.ico
  store: true
  # ---- LÍNEA CLAVE AÑADIDA ----
  # Especifica la ruta correcta de los archivos de compilación de Windows.
  build_windows_path: build\windows\x64\runner\Release
