name: controldesellos
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # PDF
  syncfusion_flutter_pdf: ^26.1.35
  syncfusion_flutter_core: ^26.1.35

  # Selección de archivos
  file_picker: 

  # Guardar archivos en dispositivo
  path_provider: ^2.0.11

  # Abrir archivos
  open_file: ^3.5.4

  # Arrastrar y soltar
  desktop_drop: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
