# Nombre del workflow que aparecerá en la pestaña "Actions" de GitHub
name: Build Windows EXE

on:
  # Se ejecuta cada vez que haces un "push" a la rama "main"
  push:
    branches: [ "main" ]
  # También permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Descarga el código de tu repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura Java (a veces requerido por dependencias de Flutter)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Configura Flutter en la máquina virtual
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.13.9' # Example of specifying a version

      # 4. Limpia caches de Flutter y pub antes de instalar dependencias
      - name: Clean Flutter & Pub cache
        run: |
          flutter clean
          flutter pub cache repair
          flutter pub get

      # 5. Run flutter doctor
      - name: Run flutter doctor
        run: flutter doctor -v

      # 6. Compila el ejecutable de Windows
      - name: Build Windows EXE
        run: flutter build windows --release

      # 7. Empaqueta los artefactos de la compilación
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: controldesellos-windows-build
          path: build/windows/x64/runner/Release/
