# .github/workflows/main.yml
name: Build Windows MSIX for Microsoft Store
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build Windows EXE
        run: flutter build windows --release
      
      # NUEVO: Verificar que los archivos de compilación existen
      - name: Verify build output
        run: |
          if (Test-Path "build\windows\x64\runner\Release\controldesellos.exe") {
            Write-Host "✓ EXE file found successfully"
            dir build\windows\x64\runner\Release
          } else {
            Write-Host "✗ ERROR: EXE file NOT found"
            dir build\windows\x64\runner\Release
            exit 1
          }
        shell: pwsh
      
      # MODIFICADO: Crear MSIX sin reconstruir
      - name: Create MSIX package for Store
        run: flutter pub run msix:create --store --build-windows false
      
      - name: Upload MSIX build artifact
        uses: actions/upload-artifact@v4
        with:
          name: controldesellos-msix-store-package
          path: build/windows/x64/runner/Release/*.msix
